### ISSUE TITLE
Incorrect default 'scope'?

### ISSUE THREAD

**Issue by philfreo** [nervetattoo/jquery-autosave#30]
The docs, https://github.com/nervetattoo/jquery-autosave#default-behavior, says that by default, scope will be

> The scope of inputs is narrowed to include only those whose value has changed since the last autosave.

But in the default callback options it appears like there isn't any scope defined:

https://github.com/nervetattoo/jquery-autosave/blob/master/src/jquery.autosave.js#L74

Which should be changed?

**Comment by philfreo** [comment]
Also the actual scope of which forms/inputs are being considered by an Autosave instances seems completely wrong.

For example I call `someSpecificEl.$('form').autosave({ ... });` and then that instance of autosave looks at ALL FORM INSTANCES on the page since `$elements.selector` is `form` and `$elements.context` is undefined. https://github.com/nervetattoo/jquery-autosave/blob/master/src/jquery.autosave.js#L107-L114

Why is there a `this.elements()` method anyway -- why doesn't it simply use whichever `$elements` were part of the $.fn.autosave() construction?

**Comment by kflorence** [comment]
To answer your first question, by default the "change" trigger is used, which has the side effect of only saving inputs that have changed since the last autosave (even though the scoping callback isn't actually used). So yes, that text is a little deceiving but also kind of correct.

As for your second question, all of that is being reworked in version 2.0. It will be using whatever element(s) are passed in, ultimately filtering the listeners down to just input elements.

If you want, you can poke around in the code here: https://github.com/kflorence/jquery-autosave/tree/2.0
Just keep in mind that it isn't quite finished yet.
